path: data/pineapple_defect

train: train/images
val: valid/images
test: test/images

nc: 4
names: ['Black spots', 'Holes', 'White fungus', 'Pineapple']

roboflow:
  workspace: pineapple-grading-system-ripeness-machine-vision
  project: pineapple-defect
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/pineapple-grading-system-ripeness-machine-vision/pineapple-defect/dataset/2