# 1. UPDATE THIS to the FULL absolute path on your computer/Colab
# Example for Colab: /content/data/pineappel_data
# Example for Windows: C:/Users/Name/Project/data/pineappel_data
path: data/pineapple_ripe

# 2. Relative paths to images (from the 'path' above)
train: train/obj
val: test/test 

# 3. Class setup
nc: 2
names: ['Immature', 'Ripe']